version: "3.8"
services:
  db:
    image: postgres
    build: ./database
    environment:
      POSTGRES_USERNAME: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "md5"
    volumes:
      - "./database/container:/usr/config"
    ports:
      - "5432:5432"
