version: "3.8"
services:
  database:
    build:
      dockerfile: "./database/dockerfile"
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - "./database/data:/var/lib/postgresql/data"
