spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DATABASE_URL}
    username: ${MIGRATION_USERNAME}
    password: ${MIGRATION_PASSWORD}
  flyway:
    enabled: true
    validate-on-migrate: true